import React,{useEffect,useState,useCallback}from'react';import*as adminApi from'../services/adminApiService';
export default function EligibilityTab({ initialExamId } = {}){const[exams,setExams]=useState([]),[students,setStudents]=useState([]),[examId,setExamId]=useState(initialExamId||''),[file,setFile]=useState(null),[preview,setPreview]=useState(null),[eligible,setEligible]=useState({items:[],total:0}),[studentId,setStudentId]=useState(''),[mode,setMode]=useState('ADD'),[error,setError]=useState(null),[message,setMessage]=useState(null),[busy,setBusy]=useState(false);
 useEffect(()=>{if(initialExamId)setExamId(initialExamId)},[initialExamId]);
 const loadExams=useCallback(async()=>{try{const r=await adminApi.listExams();setExams(r.data?.items||[])}catch(e){setError(e.message)}},[]);useEffect(()=>{loadExams();adminApi.listStudents({limit:100}).then(r=>setStudents(r.data?.items||[])).catch(e=>setError(e.message))},[loadExams]);
 const loadEligible=useCallback(async id=>{if(!id)return;try{const r=await adminApi.listEligibility(id);setEligible(r.data||{items:[],total:0})}catch(e){setError(e.message)}},[]);useEffect(()=>{setPreview(null);setStudentId('');loadEligible(examId)},[examId,loadEligible]);
 async function previewCsv(e){e.preventDefault();if(!file)return setError('Choose a CSV file first');setBusy(true);setError(null);try{const r=await adminApi.previewEligibilityCsv(examId,file);setPreview(r.data)}catch(e){setError(e.message||'CSV validation failed')}finally{setBusy(false)}}
 async function importCsv(){if(!preview)return;if(mode==='REPLACE'&&!window.confirm('Replace the current eligibility list with this import?'))return;setBusy(true);try{const r=await adminApi.importEligibility(examId,{mode,validRows:preview.valid,sourceFileName:file?.name});setMessage(`${r.data.insertedCount} students imported.`);setPreview(null);setFile(null);await loadEligible(examId)}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function addStudent(e){e.preventDefault();const s=students.find(x=>x._id===studentId);if(!s)return;setBusy(true);try{await adminApi.addEligibleStudent(examId,s._id,s.uid);setStudentId('');setMessage(`${s.name} added to eligibility.`);loadEligible(examId)}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function removeStudent(id){try{await adminApi.removeEligibleStudent(examId,id);loadEligible(examId)}catch(e){setError(e.message)}}
 const exam=exams.find(x=>x._id===examId);return <div className="admin-section"><div className="section-toolbar"><div><div className="eyebrow">Candidate access</div><h2>Exam eligibility</h2><p>Control exactly who can enter each examination. Use CSV for bulk operations or search students for individual additions.</p></div><button className="btn-secondary" onClick={loadExams}>↻ Refresh</button></div>{error&&<div className="alert alert-error">{error}</div>}{message&&<div className="alert alert-success">{message}</div>}
 <section className="panel"><div className="admin-field"><label>Examination<span className="required">*</span></label><select value={examId} onChange={e=>setExamId(e.target.value)}><option value="">Select examination…</option>{exams.map(e=><option key={e._id} value={e._id}>{e.subjectCode} · {e.examType} · {e.examDate?new Date(e.examDate).toLocaleDateString():''}</option>)}</select></div>{exam&&<div className="context-banner"><div><b>{exam.subjectCode} — {exam.examType}</b><span>{exam.status} · {exam.durationMinutes} minutes · {exam.maximumMarks} marks</span></div><strong>{eligible.total} eligible</strong></div>}</section>
 {examId&&<div className="admin-grid-2"><section className="panel"><div className="panel-head"><div><h3>Bulk import</h3><span>CSV requires one column: <code>uid</code></span></div></div><form onSubmit={previewCsv}><div className="upload-box"><input type="file" accept=".csv" onChange={e=>setFile(e.target.files?.[0]||null)}/><b>{file?.name||'Choose eligibility CSV'}</b><small>Maximum 5 MB · validated before import</small></div><button className="btn-secondary full" disabled={busy}>{busy?'Validating…':'Validate CSV'}</button></form>{preview&&<div className="preview-box"><div className="preview-stats"><span><b>{preview.totalRows}</b>Total</span><span><b>{preview.validCount}</b>Valid</span><span><b>{preview.duplicateCount}</b>Duplicates</span><span><b>{preview.unknownCount}</b>Unknown</span></div><div className="radio-row"><label><input type="radio" checked={mode==='ADD'} onChange={()=>setMode('ADD')}/> Add to existing</label><label><input type="radio" checked={mode==='REPLACE'} onChange={()=>setMode('REPLACE')}/> Replace existing</label></div><button className="btn-primary full" onClick={importCsv} disabled={!preview.validCount||busy}>Import {preview.validCount} valid students</button></div>}</section>
 <section className="panel"><div className="panel-head"><div><h3>Add individual student</h3><span>Search by name, UID or university email.</span></div></div><form onSubmit={addStudent}><SmartStudentSelect students={students} value={studentId} onChange={setStudentId}/><button className="btn-primary full" disabled={!studentId||busy}>Add to eligibility</button></form><div className="info-note"><b>Recommended</b><span>Use CSV when a complete class list is available. Individual add is useful for late corrections.</span></div></section></div>}
 {examId&&<section className="panel table-panel"><div className="panel-head"><div><h3>Eligible students</h3><span>{eligible.total} candidate{eligible.total===1?'':'s'} currently authorised</span></div></div><div className="table-wrap"><table className="data-table"><thead><tr><th>Student</th><th>UID</th><th>Email</th><th>Action</th></tr></thead><tbody>{eligible.items?.map(x=><tr key={x._id}><td><strong>{x.studentId?.name||'—'}</strong></td><td>{x.studentId?.uid||x.uid||'—'}</td><td>{x.studentId?.universityEmail||'—'}</td><td><button className="link-btn danger" onClick={()=>removeStudent(x.studentId?._id||x.studentId)}>Remove</button></td></tr>)}{!eligible.items?.length&&<tr><td colSpan="4"><div className="empty-state"><b>No eligible students</b><span>Import a class list or add an individual student.</span></div></td></tr>}</tbody></table></div></section>}
 </div>}
function SmartStudentSelect({students,value,onChange}){return <div className="admin-field"><label>Student<span className="required">*</span></label><select value={value} onChange={e=>onChange(e.target.value)}><option value="">Search/select a student…</option>{students.map(s=><option key={s._id} value={s._id}>{s.uid} — {s.name} · {s.universityEmail}</option>)}</select></div>}
